# Generated by Django 6.0 on 2026-09-07 08:16

import datetime
import re

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import crates.models.settings


class Migration(migrations.Migration):
    initial = True

    dependencies = [("bd_models", "0016_alter_player_money")]

    operations = [
        migrations.CreateModel(
            name="CratesSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "crate_name",
                    models.CharField(
                        default="crate",
                        help_text="The singular name of your crates",
                        max_length=32,
                        validators=[
                            django.core.validators.RegexValidator(
                                re.compile("^[a-z0-9_-]{1,32}$"), message="Invalid slash command name."
                            )
                        ],
                    ),
                ),
                (
                    "plural_crate_name",
                    models.CharField(
                        default="crates",
                        help_text="The plural name of your crates",
                        max_length=32,
                        validators=[
                            django.core.validators.RegexValidator(
                                re.compile("^[a-z0-9_-]{1,32}$"), message="Invalid slash command name."
                            )
                        ],
                    ),
                ),
                (
                    "crates_slash_name",
                    models.CharField(
                        default="crates",
                        help_text='Overrides "/crates" slash command',
                        max_length=32,
                        validators=[
                            django.core.validators.RegexValidator(
                                re.compile("^[a-z0-9_-]{1,32}$"), message="Invalid slash command name."
                            )
                        ],
                    ),
                ),
                (
                    "menu_color",
                    models.CharField(
                        blank=True,
                        help_text="The accent color for view containers in hex format. Leave blank for none.",
                        max_length=7,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                re.compile("^#(?:[0-9a-fA-F]{3}){1,2}$"), message="Invalid hex color format."
                            )
                        ],
                    ),
                ),
                (
                    "claim_message",
                    models.CharField(
                        default="You received one **{name}** {crate}.",
                        help_text="Sent on a successful claim.",
                        max_length=256,
                        validators=[
                            crates.models.settings.KeywordValidator(
                                "collectibles", "collectible", "discord", "bot", "crates", "crate", "name", "pool"
                            )
                        ],
                    ),
                ),
            ],
            options={"verbose_name_plural": "Settings"},
        ),
        migrations.CreateModel(
            name="Pool",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(help_text="Name of this pool, e.g. 'daily'.", max_length=32, unique=True)),
                (
                    "cooldown",
                    models.DurationField(
                        default=datetime.timedelta(days=1),
                        help_text="Time a player must wait between claims from this pool.",
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(default=True, help_text="Whether this pool can currently be claimed from."),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Crate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=64, unique=True)),
                (
                    "amount_min",
                    models.PositiveIntegerField(
                        help_text="The minimum amount of countryballs that will be given.",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "amount_max",
                    models.PositiveIntegerField(help_text="The maximum amount of countryballs that will be given."),
                ),
                (
                    "reward",
                    models.ManyToManyField(
                        blank=True,
                        help_text=(
                            "The countryballs that can be given. If blank, countryballs will be chosen at random."
                        ),
                        to="bd_models.ball",
                    ),
                ),
                ("pools", models.ManyToManyField(blank=True, related_name="crates", to="crates.pool")),
            ],
        ),
        migrations.CreateModel(
            name="CrateInstance",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("earned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "crate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="instances", to="crates.crate"
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crate_instances",
                        to="bd_models.player",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlayerPoolCooldown",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("last_claimed", models.DateTimeField()),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pool_cooldowns",
                        to="bd_models.player",
                    ),
                ),
                (
                    "pool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="player_cooldowns", to="crates.pool"
                    ),
                ),
            ],
            options={"unique_together": {("player", "pool")}},
        ),
        migrations.AddConstraint(
            model_name="crate",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount_max__gte", models.F("amount_min"))), name="amount_max_gte_amount_min"
            ),
        ),
        migrations.AddConstraint(
            model_name="crate",
            constraint=models.CheckConstraint(condition=models.Q(("amount_min__gte", 1)), name="amount_min_gte_1"),
        ),
    ]
