# Generated by Django 6.0 on 2026-09-07 08:20

from datetime import timedelta

from django.db import migrations


def create_default_pools(apps, schema_editor):
    Pool = apps.get_model("crates", "Pool")
    Pool.objects.get_or_create(name="Daily")
    Pool.objects.get_or_create(name="Weekly", cooldown=timedelta(weeks=1))


class Migration(migrations.Migration):
    dependencies = [("crates", "0001_initial")]

    operations = [migrations.RunPython(create_default_pools, reverse_code=migrations.RunPython.noop)]
