# Generated by Django 6.0.1 on 2026-09-12 11:39

import re

import django.core.validators
from django.db import migrations, models

COMMAND_NAME_RE = re.compile("^[a-z0-9_-]{1,32}$")


def format_command_name(name: str) -> str:
    formatted = name.strip().lower()
    formatted = re.sub(r"[^a-z0-9_-]+", "_", formatted)
    formatted = formatted.strip("_-") or "pool"

    return formatted[:32]


def populate_command_fields(apps, schema_editor):
    Pool = apps.get_model("crates", "Pool")
    seen_names = set(Pool.objects.exclude(command_name="").values_list("command_name", flat=True))

    for pool in Pool.objects.all():
        base = format_command_name(pool.name)
        candidate = base
        suffix = 2

        while candidate in seen_names or not COMMAND_NAME_RE.match(candidate):
            candidate = f"{base[:29]}_{suffix}"
            suffix += 1

        seen_names.add(candidate)
        pool.command_name = candidate
        pool.command_description = f"Claims a {pool.name.lower()} crate."[:100]
        pool.save(update_fields=("command_name", "command_description"))


def reverse_noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [("crates", "0003_crate_openable")]

    operations = [
        migrations.AddField(
            model_name="pool",
            name="amount_max",
            field=models.PositiveIntegerField(default=1, help_text="The maximum amount of crates that will be given."),
        ),
        migrations.AddField(
            model_name="pool",
            name="amount_min",
            field=models.PositiveIntegerField(default=1, help_text="The minimum amount of crates that will be given."),
        ),
        migrations.AddField(
            model_name="pool",
            name="command_description",
            field=models.CharField(max_length=100, null=True, help_text="Description of this pool's claim command."),
        ),
        migrations.AddField(
            model_name="pool",
            name="command_name",
            field=models.CharField(
                max_length=32,
                null=True,
                help_text="Name of this pool's claim command.",
                validators=[
                    django.core.validators.RegexValidator(COMMAND_NAME_RE, message="Invalid slash command name.")
                ],
            ),
        ),
        migrations.AddField(
            model_name="pool",
            name="conditions",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Extra requirements a player must meet to claim from this pool, on top of the cooldown.",
            ),
        ),
        migrations.RunPython(populate_command_fields, reverse_noop),
        migrations.AlterField(
            model_name="pool",
            name="command_description",
            field=models.CharField(max_length=100, help_text="Description of this pool's claim command."),
        ),
        migrations.AlterField(
            model_name="pool",
            name="command_name",
            field=models.CharField(
                max_length=32,
                unique=True,
                help_text="Name of this pool's claim command.",
                validators=[
                    django.core.validators.RegexValidator(COMMAND_NAME_RE, message="Invalid slash command name.")
                ],
            ),
        ),
        migrations.RemoveField(model_name="cratessettings", name="claim_message"),
    ]
