# Generated by Django 6.0.1 on 2026-09-14 21:48

import re

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("crates", "0004_pool_amount_max_pool_amount_min_and_more")]

    operations = [
        migrations.AddField(
            model_name="crate",
            name="emoji_id",
            field=models.BigIntegerField(
                blank=True,
                help_text="Optional emoji ID for this crate",
                null=True,
                validators=[
                    django.core.validators.RegexValidator(re.compile("^\\d{17,19}$"), message="Invalid emoji ID.")
                ],
            ),
        ),
        migrations.AlterField(
            model_name="pool",
            name="command_name",
            field=models.CharField(
                help_text="Name of this pool's claim command.",
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("^[a-z0-9_-]{1,32}$"), message="Invalid slash command name."
                    )
                ],
            ),
        ),
    ]
