# Generated by Django 6.0.1 on 2026-09-15 02:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("crates", "0005_crate_emoji_id_alter_pool_command_name")]

    operations = [
        migrations.AddField(
            model_name="crate",
            name="rarity",
            field=models.FloatField(
                default=1.0,
                help_text="Weight used when randomly picking a crate to give.",
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        )
    ]
