# Generated by Django 6.0.1 on 2026-09-15 19:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("bd_models", "0019_guildconfig_tips_enabled"), ("crates", "0006_crate_rarity")]

    operations = [
        migrations.AddField(
            model_name="crate",
            name="specials",
            field=models.ManyToManyField(
                blank=True,
                help_text=(
                    "The specials that can be given. "
                    "If blank, specials will be chosen at random with the same algorithm used when catching a ball."
                ),
                to="bd_models.special",
            ),
        )
    ]
