# Generated by Django 6.0.1 on 2026-09-15 19:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("crates", "0007_crate_specials")]

    operations = [
        migrations.AddField(
            model_name="crate",
            name="respect_ball_rarity",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "If enabled, balls in the 'rewards' field are weighted by rarity when one is "
                    "randomly selected, instead of each having an equal chance."
                ),
            ),
        ),
        migrations.AddField(
            model_name="crate",
            name="respect_special_rarity",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "If enabled, specials in the 'specials' field are weighted by rarity when one is "
                    "randomly selected, instead of each having an equal chance."
                ),
            ),
        ),
    ]
