site_name: Crates
site_author: Cayla
repo_url: https://github.com/Caylies/Crates
repo_name: Caylies/Crates
copyright: 'Copyright &copy; 2026 Cayla'

theme:
  name: material
  custom_dir: docs/overrides

  logo: assets/logo.png
  favicon: assets/logo.png

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: crate
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: crate-dark
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

  icon:
    repo: fontawesome/brands/github

  features:
    - content.code.copy
    - content.code.annotate
    - content.code.select
    - navigation.footer
    - toc.follow

nav:
  - Getting Started:
    - Overview: getting-started/overview.md
    - Configuration: getting-started/configuration.md
  - Changelog: changelog.md

markdown_extensions:
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - markdown_grid_tables
  - attr_list
  - md_in_html
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true

plugins:
  - search

extra_css:
  - stylesheets/extra.css
